### ISSUE TITLE
Charlotte login to archpull3

### ISSUE THREAD

**Issue by agstephens** [cedadev/cmip6-replication#1]
Charlotte needs to be able to log in to arch pull 3
Which user should she log in as? badc or hearnsha (herself)

**Comment by charliepascoe** [comment]
From Alan:
Here is what you will need to do to log into `arch-pull3 `.
However, I do not believe that this will yet work for you, because you need to be in group `archpullusers`.  I will ask SCD about this, and for someone to get back to you.

- From within RAL, or with VPN switched on:
   - `ssh -AX login-staff1.jasmin.ac.uk`
- Then:
   - `ssh -AX arch-pull3-mgmt`

The machine is `arch-pull3.ceda.ac.uk` but it has two network interfaces, and that address refers to the externally-facing one, which does not accept incoming ssh connections.  Hence the `-mgmt` one which refers to its internally-facing network.

**Comment by alaniwi** [comment]
@charliepascoe Sorry, I removed the comment, to avoid putting infrastructure details on a public-facing repo.

**Comment by alaniwi** [comment]
She will also need access to run commands as the user which runs synda. (I won't write the username here.) I will request this from SCD.

This is because read-only access to the database does not appear to be sufficient in order to run any synda commands, even those ones which in principle should not make changes. However, the accepted workflow will involve using it only to do a "dry run" installation to test the size, and to inspect the queue. Actual adding of selection files will be by pushing them to the repo - to be documented in detail elsewhere, but this can be done under her own username - and then letting the cron job do its thing (once this is set up).
